### ISSUE TITLE
Zend\Http\Header\SetCookie::setMaxAge doesn't conform to RFC6265 section 5.2.2

### ISSUE THREAD

**Issue by coud** [zendframework/zf2#7502]
It should not throw an exception when passing a negative value or non integer.

Zend\Http\Client doesn't work as expected because of this.

**Comment by Martin-P** [comment]
@Maks3w I think you added the wrong label to this issue. It is about `Http`, not `Mail`.

**Comment by Martin-P** [comment]
For easy reference the exact link and text: http://tools.ietf.org/html/rfc6265#section-5.2.2
> If the first character of the attribute-value is not a DIGIT or a "-" character, ignore the cookie-av.

**Comment by weierophinney** [comment]
Those of you watching this issue: please do the following in your project root:

```console
$ composer require zendframework/zendframework:dev-master@dev
```

and then test. #7507 was just merged, which should fix the issue.

**Comment by Martin-P** [comment]
@weierophinney
Please reopen this issue. You have mistaken this with the security issue, but this issue is completely unrelated to that. This issue is about setting a negative or non integer value as max-age value. The PR you are referring to does not fix this:
- where is the unittest which tests a negative value for max-age does not throw an exception?
- where is the unittest which tests a non integer value for max-age does not throw an exception?

**Comment by Maks3w** [comment]
@Martin-P Unittests are in the bag of the next person which want to help.

**Comment by weierophinney** [comment]
@Martin-P Sorry; thought this was related to ZF2015-04; I see it actually was an issue previously as well. I'll not include a fix in 2.4.2, then.

**Comment by nathanjosiah** [comment]
I'm not sure this is the right behavior change for this. Can somebody check my PR and provide some feedback?

**Comment by Martin-P** [comment]
Looking at the specs for the second time I notice the specs are about the user agent: http://tools.ietf.org/html/rfc6265#section-5.2.2
> If the attribute-name case-insensitively matches the string "Max-Age", the **user agent** MUST process the cookie-av as follows.

The question is:
do we need server-side validation of `Max-Age` at all or should we just allow any value and let the user agent decide what to do with it according to the specs?

**Comment by Martin-P** [comment]
@weierophinney @Maks3w You two are competing over this issue? Close it or open it? :smile:

**Comment by Maks3w** [comment]
Nop, just Github perfom a cross repository close because 81ccf07 has been forward to zend-http

This may to be repeat again because is automatic

**Comment by nathanjosiah** [comment]
@Martin-P if it is in the spec for the user agent I would say there doesn't need to be server validation unless it wold present a security problem otherwise which, in this case, it doesn't.

**Comment by Maks3w** [comment]
Reminder Zend\Http has Client functionallity. So this could be applied as http client (not strict means a browser)

**Comment by nathanjosiah** [comment]
@Maks3w Are you suggesting that this spec detail be implemented in the Zend\Http Clients instead?

**Comment by Maks3w** [comment]
May, I'm not sure. After component split we can review this issue again.

**Comment by Martin-P** [comment]
Ping @Maks3w @weierophinney 
f this needs a review at a later moment, please do not close this. If this GitHub again closing automatically, please remove the reference to this issue in the commit that is referring this issue!

**Comment by Maks3w** [comment]
@weierophinney said due the differences between server and client implementations this won't be addressed.

However stay tuned for propose new things in ZF3. Http component will be refactor around the PSR-7 standard (in voting yet)
